[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes=["unused-return", "unused-param", 5159]
# - "code-size"
# - "func-mutability"
# - "license"
# - "pragma-solidity"
# - "shadowing"
# - "same-varname"
# - "unreachable"
# - "unused-param"
# - "unused-return"
# - "unused-var"
# - "virtual-interfaces"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config